/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewProductsRouteImport } from './routes/view-products'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const ViewProductsRoute = ViewProductsRouteImport.update({
  id: '/view-products',
  path: '/view-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRouteWithChildren
  '/products': typeof ProductsRoute
  '/view-products': typeof ViewProductsRoute
  '/api/$': typeof ApiSplatRoute
  '/user/$id': typeof UserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRouteWithChildren
  '/products': typeof ProductsRoute
  '/view-products': typeof ViewProductsRoute
  '/api/$': typeof ApiSplatRoute
  '/user/$id': typeof UserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRouteWithChildren
  '/products': typeof ProductsRoute
  '/view-products': typeof ViewProductsRoute
  '/api/$': typeof ApiSplatRoute
  '/user/$id': typeof UserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api'
    | '/products'
    | '/view-products'
    | '/api/$'
    | '/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api'
    | '/products'
    | '/view-products'
    | '/api/$'
    | '/user/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api'
    | '/products'
    | '/view-products'
    | '/api/$'
    | '/user/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiRoute: typeof ApiRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  ViewProductsRoute: typeof ViewProductsRoute
  UserIdRoute: typeof UserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view-products': {
      id: '/view-products'
      path: '/view-products'
      fullPath: '/view-products'
      preLoaderRoute: typeof ViewProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiSplatRoute: typeof ApiSplatRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiSplatRoute: ApiSplatRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiRoute: ApiRouteWithChildren,
  ProductsRoute: ProductsRoute,
  ViewProductsRoute: ViewProductsRoute,
  UserIdRoute: UserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
